"""Emit GENERATION_REPORT.md from the frozen data. Run after generator.py.

Every number in the report is derived from the files on disk, so the report
can never drift from the dataset it describes.
"""

from __future__ import annotations

import csv
import hashlib
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
TRUTH = ROOT / "ground_truth"

CLASS_NAMES = {
    "c01_clean_1to1": "Clean 1:1 payment -> settlement",
    "c02_full_refund_pre_settlement": "Full refund before settlement (nets out)",
    "c03_partial_refund_pre_settlement": "Partial refund before settlement",
    "c04_refund_in_later_batch": "Refund lands in a LATER batch than its payment",
    "c05_subset_sum_rolled_forward": "Subset-sum exclusion -- payment rolls forward",
    "c06_netting": "Netting -- one bank credit = N payments - M refunds",
    "c07_ambiguous_decomposition": "AMBIGUOUS -- two valid subsets, same bank amount",
    "c08_dispute_hold": "Dispute hold -- on_hold true, dropped from batch",
    "c09_lost_dispute_adjustment": "Lost-dispute adjustment row (unjoinable)",
    "c10_won_dispute_settles_later": "Won dispute -- hold released, settles later",
    "c11_cross_month_boundary": "Cross-month -- created month M, settled month M+1",
    "c12_shared_sid_null_utr": "Shared settlement_id, null settlement_utr",
    "c13_schema_variance": "Schema variance -- notes {}/[]; absent credit_type",
    "c14_corrupt_bank_narration": "Corrupted/truncated bank narration",
    "c15_same_day_same_amount_decoy": "Decoy - same amount, same day, two payments",
}
UNIT = {  # what one count means
    "c06_netting": "batches", "c07_ambiguous_decomposition": "batches",
    "c14_corrupt_bank_narration": "batches",
}


def main() -> None:
    recon = json.loads((DATA / "recon_combined.json").read_text())
    rows = recon["items"]
    truth = json.loads((TRUTH / "ground_truth.json").read_text())
    bank = list(csv.DictReader((DATA / "bank_statement.csv").open()))
    erp = list(csv.DictReader((DATA / "erp_orders.csv").open()))
    gstr2b = list(csv.DictReader((DATA / "gstr2b.csv").open()))
    disputes = json.loads((DATA / "disputes.json").read_text())["items"]

    classes: Counter = Counter()
    for labels in truth["row_classes"].values():
        classes.update(labels)
    for batch in truth["batches"]:
        classes.update(batch["classes"])

    tiers = Counter(r["source_tier"] for r in rows)
    types = Counter(r["type"] for r in rows)
    methods = Counter(r["method"] for r in rows if r["type"] == "payment")
    unsettled = Counter(truth["unsettled_reason"].values())

    hard = {"c02_full_refund_pre_settlement", "c03_partial_refund_pre_settlement",
            "c04_refund_in_later_batch", "c05_subset_sum_rolled_forward",
            "c08_dispute_hold", "c09_lost_dispute_adjustment",
            "c10_won_dispute_settles_later"}
    hard_rows = {e for e, labels in truth["row_classes"].items() if hard & set(labels)}

    out = []
    w = out.append
    w("# GENERATION_REPORT.md\n")
    w("Generated by `engine/report.py` from the frozen files. Every figure below is")
    w("read off the data on disk; none is hand-written.\n")

    w("## Why this dataset is synthetic\n")
    w("Razorpay **test mode never produces settlements**. On the captured account")
    w("(`merchant_id TShuVt2nlFfcNT`) 15 payments and 2 refunds were created and")
    w("captured, the account carried a Rs 23,346.90 balance, and both")
    w("`/v1/settlements` and `/v1/settlements/recon/combined` returned `count: 0`")
    w("for every month probed. The only forcing mechanism is blocked server-side:\n")
    w("```json")
    w('{"error":{"code":"BAD_REQUEST_ERROR",')
    w(' "description":"Instant Settlements cannot be created in test mode",')
    w(' "reason":"instant_settlements_test_mode_blocked",')
    w(' "source":"business","step":"settlement_initiation"}}')
    w("```\n")
    w("Reproduced identically through REST, the hosted MCP server and the Razorpay")
    w("CLI v1.0.9; a locally built MCP server does not route around it.\n")
    w("**Settlement batching in this dataset is therefore synthesized from Razorpay's")
    w("documented behaviour, not captured.** The rule implemented is quoted verbatim")
    w("with its URL in `SETTLEMENT_SPEC.md` sec 1. No row claims to be captured")
    w("settlement data, and `source_tier` on every row says which tier it sits at.\n")

    w("## Volume\n")
    w("| quantity | value |")
    w("|---|---:|")
    w(f"| recon rows | {len(rows)} |")
    w(f"| settlement batches | {len(truth['batches'])} |")
    for name, count in sorted(types.items()):
        w(f"| &nbsp;&nbsp;of type `{name}` | {count} |")
    w(f"| disputes | {len(disputes)} |")
    w(f"| bank statement lines | {len(bank)} |")
    w(f"| ERP orders | {len(erp)} |")
    w(f"| GSTR-2B lines | {len(gstr2b)} |")
    w(f"| rows carrying >=1 hard-case label | {len(hard_rows)} "
      f"({len(hard_rows) * 100 // len(rows)}%) |")
    w("")

    w(f"## Class coverage -- all {len(CLASS_NAMES)} planted classes\n")
    w("Counts are **derived from what the simulator actually did**, not from the")
    w("construction roles. A row can carry more than one label. Class 15 is not")
    w("in the original plan -- it was added after independent audit.\n")
    w("| # | class | count | unit |")
    w("|---|---|---:|---|")
    for key in sorted(CLASS_NAMES):
        w(f"| {key[1:3]} | {CLASS_NAMES[key]} | {classes[key]} | "
          f"{UNIT.get(key, 'rows')} |")
    w("")
    missing = sorted(set(CLASS_NAMES) - set(classes))
    w(f"Classes absent: **{missing or 'none'}**\n")

    w("## Provenance -- `source_tier` distribution\n")
    w("| tier | rows | meaning |")
    w("|---|---:|---|")
    w(f"| `captured_real` | {tiers['captured_real']} | monetary and method facts "
      "copied from a real captured payment in `spike/captured_dataset.json`; ids, "
      "timestamps and `notes` CONTENT are re-issued, because the captured notes "
      "carry spike scenario labels and would leak ground truth |")
    w(f"| `synthesized_documented` | {tiers['synthesized_documented']} | grounded in "
      "a citable Razorpay statement, quoted with its URL in the spec |")
    w(f"| `synthesized_modelled` | {tiers['synthesized_modelled']} | statute or "
      "standard industry practice; **no Razorpay source** |")
    w("")
    w("`source_ref` on every row names the exact citation. Provenance is only ever")
    w("**weakened** by inheritance: a refund against a modelled card payment is")
    w("itself modelled, never promoted to its own tier.\n")

    w("### What is NOT claimed\n")
    w("- No settlement batch, and no recon row, was observed. All 12 batches are simulated.")
    w("- The fee/tax convention is verified at the **payment entity** level only.")
    w("  Whether recon rows carry the same convention is strong inference, not observation.")
    w("- Card and UPI were never observed on the captured account (card is WAF-blocked")
    w("  on the ajax path; UPI is disabled account-side). Every card and UPI row is")
    w("  tiered `synthesized_modelled`.")
    w("- Disputes cannot be created through any Razorpay interface -- `POST /v1/disputes`")
    w("  is a routing-layer HTTP 404. All dispute behaviour is modelled.\n")

    w("## Method mix\n")
    w("| method | payments |")
    w("|---|---:|")
    for name, count in sorted(methods.items(), key=lambda kv: -kv[1]):
        w(f"| {name} | {count} |")
    w("")
    w("The captured account produced netbanking x9 and wallet x3 only -- card is")
    w("WAF-blocked on the ajax seeding path and UPI is disabled account-side. The")
    w("mix here is UPI-dominant by count, as an Indian merchant book is in 2026,")
    w("and every card and UPI row is tiered `synthesized_modelled` accordingly.")
    w("Card rows exist so `card_network` / `card_issuer` / `card_type` and the")
    w("three MDR tiers (2% default, 3% Amex/Diners, 0% RuPay debit) are exercised")
    w("rather than dead.\n")
    w("**UPI is billed at 2%, not zero.** Zero-MDR under Sec 269SU binds banks and")
    w("system providers, not the aggregator's platform fee, and Razorpay's")
    w("published pricing charges it. An earlier draft of this dataset priced UPI")
    w("at zero; that was a false claim about a vendor's own commercials and it was")
    w("corrected before the freeze.\n")

    w("## Why rows did not settle\n")
    w("| reason | rows |")
    w("|---|---:|")
    for reason, count in sorted(unsettled.items()):
        w(f"| `{reason}` | {count} |")
    w("")
    w("Nothing vanishes: every unsettled row has a stated reason, asserted by")
    w("`tests/test_balance_closure.py::test_every_excluded_payment_is_accounted_for`.\n")

    w("## Batches\n")
    w("| # | formed | pool | live balance | selected credit | credit col | "
      "debit col | bank payout | ambiguous |")
    w("|---:|---|---:|---:|---:|---:|---:|---:|:-:|")
    for i, b in enumerate(truth["batches"]):
        marks = []
        if b["ambiguous"]:
            marks.append("**YES**")
        if b.get("tying_decompositions_truncated"):
            marks.append("(truncated)")
        if b.get("selection_degraded"):
            marks.append("(FIFO fallback)")
        w(f"| {i} | {b['formed_on']} | {b.get('pool_size', '')} | "
          f"{b['available_live_balance']} | "
          f"{b['selected_payment_credit']} | {b['credit_total']} | "
          f"{b['debit_total']} | {b['bank_payout']} | "
          f"{' '.join(marks) or '-'} |")
    w("")
    w("All amounts in paise. `selected credit` is the quantity the documented rule")
    w("constrains and never exceeds `live balance`. `credit col - debit col ==")
    w("bank payout` on every batch, with zero residual.\n")

    amb = [b for b in truth["batches"] if b["ambiguous"]]
    w("## The provably-unresolvable class\n")
    w(f"{len(amb)} of {len(truth['batches'])} batches admit more than one valid")
    w("decomposition of the same bank credit:\n")
    w("| settlement_id | bank payout | tying decompositions |")
    w("|---|---:|---:|")
    for b in amb:
        w(f"| `{b['settlement_id']}` | {b['bank_payout']} | "
          f"{len(b['tying_decompositions'])} |")
    w("")
    w("The shipped data carries **no marker** of which batches these are. A solver")
    w("that returns a single confident decomposition for one of them is wrong even")
    w("when it names the same subset the simulator picked, because it could not have")
    w("known. `tests/test_ambiguity.py` encodes that contract and was written before")
    w("any solver existed.\n")

    w("## Declared plants — including the ones that did not land\n")
    w("A generator that can silently under-deliver its hardest class is a")
    w("generator whose output means nothing. Every declared plant is recorded")
    w("here whether or not it succeeded.\n")
    w("| kind | batch | planted | detail |")
    w("|---|---:|:-:|---|")
    for entry in truth["planted_ambiguity"]:
        detail = entry.get("reason", entry.get("settlement_id", ""))
        w(f"| ambiguity | {entry['batch_index']} | "
          f"{'yes' if entry['planted'] else '**no**'} | {detail} |")
    for entry in truth["planted_balance_pressure"]:
        detail = (f"excluded {entry['excluded_credit']} paise"
                  if entry.get("planted") else entry.get("reason", ""))
        w(f"| balance pressure | {entry['batch_index']} | "
          f"{'yes' if entry['planted'] else '**no**'} | {detail} |")
    w("")

    w("## ITC at risk (companion GST reconciliation)\n")
    w("Three distinct statutory grounds. The Rule 37A case is the interesting")
    w("one: GSTR-2B still reports the credit as available, so an engine has to")
    w("compute the exposure rather than read it off.\n")
    w("| invoice | period | ground | provision | tax at risk (paise) |")
    w("|---|---|---|---|---:|")
    for entry in truth["itc_at_risk"]:
        w(f"| `{entry['invoice_no']}` | {entry['period']} | {entry['reason']} | "
          f"{entry['statute']} | {entry['itc_paise']} |")
    w("")
    w("### GST rounding residuals\n")
    w("A consolidated invoice computes GST once on the aggregate; the ledger")
    w("accrues ceiling-rounded tax per transaction. The gap is real and is")
    w("recorded rather than forced to match.\n")
    w("| period | accrued tax | invoiced tax | residual | fee charged without GST |")
    w("|---|---:|---:|---:|---:|")
    for entry in truth["gst_rounding_residuals"]:
        w(f"| {entry['period']} | {entry['accrued_tax_paise']} | "
          f"{entry['invoiced_tax_paise']} | {entry['residual_paise']} | "
          f"{entry['fee_charged_without_gst_paise']} |")
    w("")

    w("## Freeze\n")
    w("`DATASET_HASHES.txt` carries the SHA-256 of every data file **and of the")
    w("ground-truth key**.\n")
    w("**What it proves and what it does not.** A hash file is *tamper")
    w("detection*: it shows the committed data is exactly what the committed")
    w("generator produces, so the bytes cannot be quietly hand-edited after the")
    w("fact. It is **not** proof of authorship order — a file cannot attest to")
    w("what did not yet exist beside it. And because the dataset is a pure")
    w("function of one seed, a timestamp could not detect seed-shopping either.")
    w("The answer to that attack is `ROBUSTNESS.md`, which shows the planted")
    w("classes survive twenty seeds nobody chose.\n")
    w("```")
    for line in (ROOT / "DATASET_HASHES.txt").read_text().splitlines():
        if line and not line.startswith("#"):
            w(line)
    w("```\n")
    w("Verify with `shasum -a 256` against the paths above, or run")
    w("`pytest engine/tests/test_determinism.py`, which re-runs the generator from")
    w("seed and asserts the committed bytes are exactly what it produces.\n")

    w("## Reproduce\n")
    w("```bash")
    w("python3 engine/generator.py --seed 20260822")
    w("python3 engine/report.py")
    w("python3 engine/robustness.py --seeds 20      # multi-seed sweep, slow")
    w("pytest engine/tests/ -q")
    w("```")

    (ROOT / "GENERATION_REPORT.md").write_text("\n".join(out) + "\n")
    print(f"wrote {ROOT / 'GENERATION_REPORT.md'}")


if __name__ == "__main__":
    main()
